# Generated by Django 4.2.7 on 2025-10-17 22:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('category', models.CharField(choices=[('birthday', 'Birthday Parties'), ('corporate', 'Corporate Events'), ('school', 'School Activities'), ('cultural', 'Cultural Events'), ('stem', 'STEM Learning'), ('inclusive', 'Inclusive Play')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
                'ordering': ['-created_at'],
            },
        ),
    ]
