# Generated by Django 4.2.7 on 2025-10-17 22:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_range', models.CharField(help_text="e.g., 'UGX 500,000 - 1,000,000'", max_length=100)),
                ('category', models.CharField(choices=[('birthday', 'Birthday Parties'), ('corporate', 'Corporate Events'), ('school', 'School Activities'), ('cultural', 'Cultural Events'), ('stem', 'STEM Learning'), ('inclusive', 'Inclusive Play')], max_length=20)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
